AWSTemplateFormatVersion: 2010-09-09
Description: >-
  lambda-auth

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  JWTSecret:
    Type: "String"
    Description: "JWT Secret key for token generation"
    Default: "secret"

Resources:
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: login/app.handler
      CodeUri: ./built
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 10
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        LoginEvent:
          Type: Api
          Properties:
            Path: /login
            Method: post
      Environment:
        Variables:
          JWTSecret: !Sub "${JWTSecret}"
  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: authorizer/app.handler
      CodeUri: ./built
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 10
      Description: A lambda function authorizer that validates JWT tokens.
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          JWTSecret: !Sub "${JWTSecret}"
